### PR TITLE
Enable OSX

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Not sure about these errors:
```
In file included from /Users/travis/build/xtensor-stack/xtensor-zarr/test/test_zarr.cpp:12:
In file included from /Users/travis/miniconda/envs/test/include/xtensor/xview.hpp:20:
/Users/travis/miniconda/envs/test/include/xtl/xclosure.hpp:26:20: error: no template named 'add_const_t' in namespace 'std'; did you mean 'add_const'?
    constexpr std::add_const_t<T>& as_const(T& t) noexcept
              ~~~~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:1030:50: note: 'add_const' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS add_const
                                                 ^
```

**Comment by JohanMabille** [comment]
Superseded with #9

**Comment by davidbrochart** [comment]
You meant #10

**Comment by JohanMabille** [comment]
yes ;)

**Pull request closed without merging**
